### ISSUE TITLE
Documentation format broken on v0.11.4

### ISSUE THREAD

**Issue by danielcj** [tfwright/live_admin#102]
**Describe the bug**
The documentation on hexdocs is not formatted correctly for version v0.11.4. It was good on version v0.11.3.
https://hexdocs.pm/live_admin/0.11.4/readme.html

**To Reproduce**
1. Go to https://hexdocs.pm/live_admin/0.11.4/readme.html
2. See that the format is not correct

**Expected behavior**
The documentation should be formatted correctly.

**Screenshots**
<img width="1582" alt="image" src="https://github.com/tfwright/live_admin/assets/64300/e05c0def-15e2-4d7a-ba9b-b0a0ca47b237">

**Environment:**
 - Chrome

**Comment by danielcj** [comment]
I suppose this is actually fixed on main;

**Comment by tfwright** [comment]
Yep, I thought I already pushed the fix, but should be live now!
