### ISSUE TITLE
LiveAdmin errors with lists of maps

### ISSUE THREAD

**Issue by tmaszk** [tfwright/live_admin#105]
**Describe the bug**
LiveAdmin errors when record has field of type `{:array, :map}`.  For example, it is the type that Oban uses to store errors on [%Oban.Job{}](https://github.com/sorentwo/oban/blob/3e9f936976bbe90c04791d7da3dfea1a0f3571cf/lib/oban/job.ex#L137)

**To Reproduce**
1. Add Oban jobs table to LiveAdmin
2. When an Oban Job has an error, the `errors` column contains one or more error maps
3. Click on the Oban.Jobs table in LiveAdmin

**Expected behavior**
Show the values in the list of maps

**Screenshots**
![Screenshot 2024-03-10 at 2 10 53 PM](https://github.com/tfwright/live_admin/assets/4540522/a41fb3e4-623c-48e9-be91-56152a9d0d82)

**Environment:**
 - OS: any
 - Browser any
 - Version main

Note
This is similar to the issue I reported earlier with arrays of strings.

**Comment by tfwright** [comment]
Fixed in https://github.com/tfwright/live_admin/commit/6d6490e54311212488bc857223dc5a85f59c5f94
