### ISSUE TITLE
Suggestion: move buttons and summary outside of table

### ISSUE THREAD

**Issue by tmaszk** [tfwright/live_admin#106]
**Describe the bug**
This is a suggestion, not a bug.  I hope you don't mind.  I think you have a great package here and my goal is only to help improve it.

When viewing a table, the Prev/Next buttons and "XX total rows" are rendered inside the table.  When the rows are large, this prevents you from accessing the buttons or seeing the total number of records without having to scroll all the way to the right or left.

I would rather see those buttons and row total rendered outside the table so I could see both without having to horizontally scroll.

**To Reproduce**
1. Go to a table with enough fields that the table has to horizontally scroll to see the entire record.
2. Notice that the buttons are only visible if you scroll all the way to the left, while the total number of rows is only visible if you scroll all the way to the right.

**Expected behavior**
See buttons and row total without having to scroll.

**Screenshots**
![Screenshot 2024-03-13 at 9 32 09 AM](https://github.com/tfwright/live_admin/assets/4540522/9b49a3ac-32a9-41e1-8e44-fec2cf49e81d)
![Screenshot 2024-03-13 at 9 32 37 AM](https://github.com/tfwright/live_admin/assets/4540522/acc28e21-515a-48c3-8cab-54b4131ae862)
![Screenshot 2024-03-13 at 9 32 54 AM](https://github.com/tfwright/live_admin/assets/4540522/4d310da3-1a64-45ea-a889-673e1c2cc592)

**Environment:**
 - OS: any
 - Browser any
 - Version main

**Additional context**
Thanks!

**Comment by tfwright** [comment]
Hi again @tmaszk 

I am happy to consider that. I can't recall any particular reason they are in the table currently. Would you mind reopening this issue in the discussions tab? I am currently only using issues for bugs: https://github.com/tfwright/live_admin/discussions
