### ISSUE TITLE
Dockerfile image (1.15.7-erlang-25.3.2.7-debian-buster-20230612-slim) outdated for ranch_server

### ISSUE THREAD

**Issue by gzzengwei** [tfwright/live_admin#111]
**Describe the bug**
docker image for elixir/erlang is outdated

**To Reproduce**
1. clone the repo
2. run `docker compose up`
3. container failed to start and container exited

```
live_admin-app-1 | [error] beam/beam_load.c(190): Error loading module ranch_server:
live_admin-app-1 | This BEAM file was compiled for a later version of the runtime system than the current (Erlang/OTP 25).
live_admin-app-1 | To fix this, please re-compile this module with an Erlang/OTP 25 compiler.
live_admin-app-1 | (Use of opcode 181; this emulator supports only up to 180.)
```

**Expected behavior**
app should be able to spin up

**Screenshots**
<img width="2225" alt="live_admin_error" src="https://github.com/tfwright/live_admin/assets/656662/0d6166d2-687f-422e-bf24-e850c4f75790">

**Environment:**
 - OS: MacOS
 - Browser Firefox

**Additional context**
upgrade image tag to: elixir:1.16.3-erlang-26.2.5.1-debian-buster-20240612-slim
will fix the issue

**Comment by tfwright** [comment]
Hi @gzzengwei that error suggests that the project was compiled with a different Erlang version before attempting to use the docker compose file. Is that possible? Did you try clearing out the `_build` directory before running `docker compose up`?
