### ISSUE TITLE
Edit and view Associations

### ISSUE THREAD

**Issue by AlexParamonov** [tfwright/live_admin#15]
Hello,

First of all, you did a great job with embedded schemas: it works out of the box and saves perfectly, even for custom types! Impressive, other admin solutions failed to do so!

Unfortunately, all other schema-to-schema or table-to-table associations (1 to many, many to many) can only display a disabled `id` field. 
Is there a way to render such associations similar to embedded ones? Could you please let me know where help is needed and what is already in progress? 

Best,
Alexander

**Comment by AlexParamonov** [comment]
Hm, does it work with `binary_id`?

I have the schema:
```elixir
defmodule Schema.ConversationMessage do
  use Schema.UUID
  import Ecto.Changeset

  schema "conversation_messages" do
    belongs_to :conversation, Schema.Conversation
    belongs_to :participant, Schema.User

    field :content, :string

    timestamps()
  end

  @doc false
  def validate(message) do
    message
    |> validate_required([:content])
  end
end
```

Keys in db:
```csv
table_schema,constraint_name,table_name,column_name,foreign_table_schema,foreign_table_name,foreign_column_name
public,conversation_messages_conversation_id_fkey,conversation_messages,conversation_id,public,conversations,id
public,conversation_messages_participant_id_fkey,conversation_messages,participant_id,public,users,id
```

Live Admin UI:
![image](https://user-images.githubusercontent.com/352030/199612698-5c2dd9d2-ae64-4fe4-b3a9-6da3c0eac2c0.png)

**Comment by tfwright** [comment]
Hm, I don't think editing binary ids are currently fully supported. Adding support might be as easy as updating [this guard clause ](https://github.com/tfwright/live_admin/blob/af3b5765897952861564d7c9fe61355922f1d516/lib/live_admin/components/resource/form.ex#L225-L255) but I would need to look into that a bit more.

**Comment by tfwright** [comment]
@AlexParamonov this seemed pretty straightforward to add so I went ahead and implemented it in https://github.com/tfwright/live_admin/commit/27dee2e8143e034814630fb943dbd006ad74432f

When you have a chance, can you try out that ref in your app, and let me know how it works?

**Comment by AlexParamonov** [comment]
@tfwright It works like a charm!

**Comment by AlexParamonov** [comment]
Thanks a lot for the swift update!
