### ISSUE TITLE
it's requiring phoenix_view

### ISSUE THREAD

**Issue by maysam** [tfwright/live_admin#27]
I am getting

`** (CompileError) lib/live_admin/view.ex:4: module Phoenix.View is not loaded and could not be found`

is'nt this supposed to be fully liveview?

**Comment by tfwright** [comment]
`phoenix_view` is a dep of `phoenix/phoenix_live_view` before 1.7. I assume you are using 1.7?

Which version of live_admin?

**Comment by maysam** [comment]
yes I am using 1.7 and latest version of live_admin

btw adding phoenix_view to mix didn't help either

**Comment by tfwright** [comment]
Hm, OK, adding it as a dep is what I was going to suggest, as I think that has worked for others. If I switch to 1.7 the dev app works fine. Can you share your mix.lock?

**Comment by tfwright** [comment]
Alternatively, make sure you are specifying 2x `{:phoenix_view, "~> 2.0"},` or use the latest main instead of a hex version.

**Comment by maysam** [comment]
<img width="484" alt="image" src="https://user-images.githubusercontent.com/591033/221478555-6a9f9c05-7800-4437-99c1-aebcb5449686.png">

can you tell me why you removed it again?

**Comment by maysam** [comment]
dependency is removed

not sure if it's relevant, but I also get
`** (Mix) Could not start application phoenix_view: could not find application file: phoenix_view.app`

**Comment by maysam** [comment]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/591033/221483985-d23163b6-819f-43f8-a546-a4cbf58eff1c.png">

I got it working, but ... doesn't open and I cannot edit or delete records

**Comment by tfwright** [comment]
I won't be able to help troubleshoot your issue without more specific info about your version (git ref is best), error messages your seeing (if any), browser you're using, other deps etc.

**Comment by tfwright** [comment]
Since your original issue has been solved, I'm closing this to reduce noise/confusion. I enabled templates, so if you are still having problems, open a new issue using the bug report template which will help gather/organize relevant info. Thanks!
