### ISSUE TITLE
fails to compile

### ISSUE THREAD

**Issue by pyladune** [tfwright/live_admin#39]
**Describe the bug**

== Compilation error in file lib/live_admin/view.ex ==
** (CompileError) lib/live_admin/view.ex:4: module Phoenix.View is not loaded and could not be found
    (elixir 1.14.4) expanding macro: Kernel.use/2
    lib/live_admin/view.ex:4: LiveAdmin.View (module)

Brand new app generated by mix phx.new and gen.auth 
phoenix 1.7.5, liveview 0.19.2

**Comment by tfwright** [comment]
Which version of LiveAdmin are you using?

**Comment by pyladune** [comment]
0.7.3 also fails with liveview 0.19
so for now, last possible liveview is 0.18.3

**Comment by tfwright** [comment]
It didn't look like there should be any breaking changes in 0.19 so I have bumped the version in main. After I've had a chance to do a bit more testing I will backport that upgrade to 0.7.x and 0.8.x. In the meantime you can try locking to 3adc9a6c09483838244f483a9ca3f0b9e421e8e2 but there are various changes still in dev there so I can't guarantee it's stable.

**Comment by tfwright** [comment]
Resolved in https://github.com/tfwright/live_admin/commit/3adc9a6c09483838244f483a9ca3f0b9e421e8e2
