### ISSUE TITLE
BUG: Ecto.Enum no longer selects?

### ISSUE THREAD

**Issue by Rio517** [tfwright/live_admin#44]
This might be the intended behavior or a regression, so I'm reluctant to make this a bug ticket. I noticed in 0.8.0 that Ecto.Enum fields would be a select input with the options nicely set-up. In main, at least as of 31f76dcec8d65a72ac6f97fb0bb4a40cb99836e9, the fields now render as textareas. Example of currently rendered HTML:

```
<div class="field__group field__enum">
  <label class="field__label" for="params_status">Status</label>
      <textarea disabled="" id="params_status" name="params[status]" rows="1">:talent_interest_pending</textarea>  
</div>
```

**Comment by tfwright** [comment]
Yeah that's a regression, enums should be a select
