### ISSUE TITLE
live_admin route throws "invalid resource" 

### ISSUE THREAD

**Issue by giusdp** [tfwright/live_admin#46]
**Describe the bug**

Great library! I'm using the latest version 0.8.2. 
I'm having a problem following the setup guide.
The `live_admin` route in the router from the README is not working. The lib is not picking up
the resource, giving me an "invalid resource" error, although it is an Ecto schema.

 Using the syntax from the hex docs `live_admin "/admin", resources: [MyApp.SomeEctoSchema]` works instead.

**To Reproduce**
Follow the small setup in the README in a new project

**Environment:**
 - OS: ubuntu 23
 - Browser: firefox
 - LiveAdmin: 0.8.2
 - LiveView: 0.19

**Comment by tfwright** [comment]
The config api has significantly changed in main. The correct README should be available in the official docs: https://hexdocs.pm/live_admin/readme.html

**Comment by giusdp** [comment]
Oh got it, thanks!
