### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Rio517** [tfwright/live_admin#52]
Thanks so much for creating this awesome library.  I just noticed how to use render_with.  Super helpful!

I have two requests:

* **Allow links/redirects in record actions menu**, with a way to pass the current record - In my case, I'd like to link to a preview page and a page with a specialized form that is outside of the scope of an edit page.
* **Configure index table fields and order**  - I'd love to be able to order and hide some.

If I have overlooked existing capabilities, please let me know!

Thanks!

-Mario

**Comment by tfwright** [comment]
Glad to hear you're finding the lib useful!

**Comment by tfwright** [comment]
(Also there is the :hidden_fields option, but I'm assuming you want something specific to list view?)

**Comment by Rio517** [comment]
Is there a way to specify custom rendering of foreign key fields (org_id)?  I noticed that these fields don't seem to go through the render_field function. I was trying to specify how to handle those in `:render_with` .

**Comment by tfwright** [comment]
I'll need to check to be sure but that sounds like a bug. I think they should go through the same render flow as any other field, just the default should be different.
