### ISSUE TITLE
foreign key fields skip `render_field`

### ISSUE THREAD

**Issue by Rio517** [tfwright/live_admin#59]
It seems to be impossible to customize the rendering of foreign key fields (org_id)?  These fields don't seem to go through the `render_field` function. I was trying to specify how to handle those in `:render_with` .

_Originally posted by @Rio517 in https://github.com/tfwright/live_admin/issues/52#issuecomment-1636741908_

**Comment by tfwright** [comment]
Resolved in https://github.com/tfwright/live_admin/commit/28004c9921c2cf78522f7fd53a7cb24487c0843f
