### ISSUE TITLE
Array values getting dropped

### ISSUE THREAD

**Issue by Rio517** [tfwright/live_admin#63]
When validating or updating a record, the checked values for array fields get dropped. 

For example, option one is checked, after validating, option one would be unchecked.

```
<div class="checkbox__group">
  <input id="params_additional_skills" name="params[additional_skills][]" type="hidden">
  
    <input checked="" id="params_additional_skillsone" name="params[additional_skills][]" type="checkbox" value="one">
    <label for="params_additional_skillsone">
      one
    </label>
  
    <input id="params_additional_skillstwo" name="params[additional_skills][]" type="checkbox" value="two">
    <label for="params_additional_skillstwo">
      two
    </label>
  
    <input id="params_additional_skillsthree" name="params[additional_skills][]" type="checkbox" value="three">
    <label for="params_additional_skillsthree">
      three
    </label>
  
    <input id="params_additional_skillsfour" name="params[additional_skills][]" type="checkbox" value="four">
    <label for="params_additional_skillsfour">
      four
    </label>
</div>
````

This is without using `validate_with` or `save_with` options on version 10.1

**Comment by Rio517** [comment]
Ok. Ill try to create a demo app.

**Comment by tfwright** [comment]
The dev app has an example of an enum array field: https://github.com/tfwright/live_admin/blob/c92f5be3c7818b0aa1ac88e7a5a8d5e2c18ef2ed/dev.exs#L179

The only thing I could different in your field definition is the default, but even after adding that, updating that field seems to work fine with none of the unexpected behavior you describe above.

**Comment by Rio517** [comment]
Finally, the new info!

The checkbox app does work until you add an embeds_many.  I [added a commit](https://github.com/Rio517/live_admin_issue/commit/37c6a7b6f78c089f07e75b7c34eff64f62695b79) to demonstrate the problem, also seen in this video. 

Thanks in advance for reopening this issue!



https://github.com/tfwright/live_admin/assets/14241/8714fc1d-2f63-4dcc-a1e0-f109dc373a8c

**Comment by tfwright** [comment]
@Rio517 it doesn't look like your video upload worked? I checked on the dev app and it includes an example of editing an embeds_many with a array enum that appears to work fine

**Comment by tfwright** [comment]
Also, instead of a separate app, it would actually be even more helpful if you could edit the dev app code to reproduce the issue there. Since it involves an embed, it shouldn't even require db changes

**Comment by Rio517** [comment]
Sure. I can take a look and ensure the dev app replicates the behavior.  For clarity, here is the video again.

https://github.com/tfwright/live_admin/assets/14241/98eda07f-10fa-4ea7-95a8-c9b585b28f39

**Comment by tfwright** [comment]
Still won't load for me :(

![Screenshot 2023-08-23 at 3 48 45 PM](https://github.com/tfwright/live_admin/assets/501/076c6a19-9d62-4eb9-884c-3f3747c6cef3)

**Comment by Rio517** [comment]
Ergh! Frustrating that I can see it fine. 

Link: https://imgur.com/a/5KlgLWN

**Comment by tfwright** [comment]
OK, I can see that, but I still can't replicate


https://github.com/tfwright/live_admin/assets/501/92f0ac46-08b9-41ab-89f4-ad10566bbdf2

What OS/browser are you using?

**Comment by Rio517** [comment]
We have seen this behavior in both Chrome on Linux and Chrome on Mac.

I'm trying to test with your dev.exs app, but am stuck with an error when running trying to get the container up `docker compose up`

Error: Cannot find module 'esbuild'
web_1  | Require stack:
web_1  | - /opt/app/assets/esbuild.js

I'll have to investigate when I can, but it is late where I am so I have to head to bed.

**Comment by Rio517** [comment]
I don't see the same issue in your single-page dev.exs app. However, I do see the issue in the live_admin Phoenix app I created and in my production app. Keep in mind, my demo app is really the minimum I could do to a brand-new phoenix app to recreate the issue. My guess is it is the more common case.  

https://github.com/Rio517/live_admin_issue

I will spend some time aligning your dev.ex with my demo app to see if I can replicate the issue in your dev.exs.

**Comment by tfwright** [comment]
Good news, I was finally able to replicate using your app, as well as with the dev app.  It looks like it affects records with _existing_ value set for the enum array. To reproduce you just need to save a record with a value checked on the enum array and then add a new embed.

**Comment by tfwright** [comment]
https://github.com/tfwright/live_admin/commit/9ea25d2b0f174f83be4d00ea4a0f76636ee99578

So it turns out this wasn't related to embeds at all, but rather the implementation of the checkbox array. Apparently when applying form changes for enums, `input_value` will return the string representation of the enum value instead of the atom.

**Comment by Rio517** [comment]
Thanks so much for finding that! What great news!
