### ISSUE TITLE
Can't assign belongs to relationship value via new or edit forms

### ISSUE THREAD

**Issue by jakespracher** [tfwright/live_admin#84]
**Describe the bug**
Thanks for the package. I have two schemas, user and conversation, where conversation belongs to user

```
defmodule Grayrock.Users.User do
  use Ecto.Schema
  use LiveAdmin.Resource
  import Ecto.Changeset
  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  @derive {
    Flop.Schema,
    default_limit: 20,
    filterable: [:search_phrase, :email, :confirmed_at, :inserted_at],
    sortable: [:email, :confirmed_at, :inserted_at],
    compound_fields: [search_phrase: [:email]]
  }
  schema "users" do
    field :email, :string
    ...
  end
```

(boilerplate from https://livesaaskit.com)

```
defmodule MyApp.Chatbot.Conversation do
  use Ecto.Schema
  use LiveAdmin.Resource
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "chatbot_conversations" do
    ...
    belongs_to :user, Grayrock.Users.User
```

I am unable to assign a value to the user field via the conversation form (see video)

https://github.com/tfwright/live_admin/assets/7165897/c2dc3951-0ac3-4ec5-98f5-98e37d76e961

**To Reproduce**
1. Setup app / database with above schemas and panel following readme instructions
2. Visit conversation form
3. Go create or edit a conversation
4. Attempt to set the user field
5. See video

**Expected behavior**
Something would show in these places:

<img width="265" alt="Screenshot 2023-12-02 at 9 55 58 PM" src="https://github.com/tfwright/live_admin/assets/7165897/410dea9f-00b8-4866-8dcb-7af1f47a3d86">

<img width="146" alt="Screenshot 2023-12-02 at 9 56 06 PM" src="https://github.com/tfwright/live_admin/assets/7165897/22bb665b-5ff5-488f-8fe4-0789b092d71f">

**Environment:**
- Elixir 1.15.7
- {:live_admin, "~> 0.11.2"},
- Phoenix 1.7.9
 - macOS 13.4.1 
 - safari 16.5.2 

**Additional Context**
No errors shown in phoenix server logs or browser js console, everything else seems to work as expected

**Comment by tfwright** [comment]
Thanks for the report. What version of live_admin are you using?

**Comment by jakespracher** [comment]
0.11.2

**Comment by tfwright** [comment]
Sorry for the delay on this. I have verified the issue affecting Safari on MacOS, will look into a fix soon.

**Comment by tfwright** [comment]
So unfortunately this seems to be a Safari quirk that, as least from what I can see, breaks not only the search select but also dropdowns throughout the app. I don't see any easy fix that doesn't involve reimplementing all of these components so I can't promise any resolution in the near term, given my extremely lackluster FE dev skills.

**Comment by tfwright** [comment]
This should be fixed in main.

It turned out the issue with the dropdowns was relatively simple: https://github.com/tfwright/live_admin/commit/0234a26eb4f487e0994b2eaa19798e7337225990

That still didn't fix the search select, and I wasn't able to figure out exactly why, but reasoning that it must be a slightly different markup used there vs other dropdowns which were now working correctly, I was able to fix it by refactoring the general dropdown component to support the search select UX: https://github.com/tfwright/live_admin/commit/341f8a820a4f50e9379894ace80add992af11cc8

Please let me know if you encounter further issues

**Comment by jakespracher** [comment]
Confirming this is resolved after update. Thanks!
